// export const ADD_TODO = 'ADD_TODO';
// export const DELETE_TODO = 'DELETE_TODO';
// export const EDIT_TODO = 'EDIT_TODO';
// export const COMPLETE_TODO = 'COMPLETE_TODO';
// export const COMPLETE_ALL = 'COMPLETE_ALL';
// export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const ADD_FILE = 'ADD_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const GET_FILE_INFO_REQUEST = 'GET_FILE_INFO_REQUEST';
export const GET_FILE_INFO_REQUEST_SUCCESS = 'GET_FILE_INFO_REQUEST_SUCCESS';
export const GET_FILE_INFO_REQUEST_FAILURE = 'GET_FILE_INFO_REQUEST_FAILURE';
